name: "Assert no changes"
description: "Assert there are no changes (tracked or untracked) visible to git"
runs:
  using: "composite"
  steps:
    - name: Assert no changes
      shell: bash
      run: |
        git status --porcelain=v1
        exit $( git status --porcelain | head -1 | wc -l )
