name: "Run e2e tests"
description: "Run e2e tests"
inputs:
  args:
    description: Arguments to pass into playwright
    required: true
  artifact-postfix:
    description: Postfix to append to the artifacts created by this run
runs:
  using: "composite"
  steps:
    - name: Install Playwright browsers
      run: pnpm playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm run e2e:ci ${{ inputs.args }}"
      env:
        DEBUG: "pw:webserver"

    - name: Upload blob report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: "blob-report-${{ inputs.artifact-postfix }}"
        path: blob-report
        retention-days: 1

    - name: Upload traces
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: "traces-report-${{ inputs.artifact-postfix }}"
        path: test-results
        retention-days: 1
        if-no-files-found: ignore

    - name: Upload wrangler logs
      if: ${{ !cancelled() && failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: "web-server-logs-${{ inputs.artifact-postfix }}"
        path: /home/runner/.config/.wrangler/logs/**/*.log
        retention-days: 1
        if-no-files-found: ignore
