on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  validations:
    name: Run validations
    uses: ./.github/workflows/validations.yml
  deploy:
    name: Deploy to Cloudflare Pages
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    runs-on: ubuntu-latest
    needs: [validations]
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build
        uses: ./.github/actions/build

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
