on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  validations:
    name: Run validations
    uses: ./.github/workflows/validations.yml
  e2e_validations:
    name: Run e2e validations
    uses: ./.github/workflows/e2e.yml
  deploy:
    name: Deploy to Cloudflare Pages
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
    runs-on: ubuntu-latest
    needs: [validations, e2e_validations]
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Build
        id: build
        uses: ./.github/actions/build

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy --branch ${{ github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Smoke Test Deployment
        uses: ./.github/actions/e2e
        with:
          args: "--config playwright.postrelease.config.ts --project='ChromiumSmokeTest'"
          artifact-postfix: "Smoke-Test"
        env:
          PW_BASE_URL: ${{ github.ref == 'refs/heads/main' && 'https://faux.joshuaen.com' || steps.deploy.outputs.deployment-url }}
          PW_APP_VERSION: ${{ steps.build.outputs.version }}
