name: Validations

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  validate:
    name: "General"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Typecheck
        run: pnpm run typecheck
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test:ci

      - name: "> Assert no initial changes"
        uses: ./.github/actions/assert-no-changes

      - name: "Recreate recursive fast lookups"
        run: pnpm run script:create-recursive-fast-lookups
      - name: "> Assert no changes"
        uses: ./.github/actions/assert-no-changes

      - name: "Run short circuit solve"
        run: pnpm run script:short-circuit:full-solve --solver community-data-recursive-fast
      - name: "> Assert no changes"
        uses: ./.github/actions/assert-no-changes

  validate-full-solve:
    name: "Full Solve"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: "> Assert no initial changes"
        uses: ./.github/actions/assert-no-changes
      - name: "Run full solve"
        run: pnpm run script:full-solve --solver community-data-recursive-fast --skip-existing-solves false
      - name: "> Assert no changes"
        uses: ./.github/actions/assert-no-changes
